services:
  backend:
    image: backend
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    env_file:
      - path: ./bloglist-backend/.env
    container_name: backend

  frontend:
    image: frontend
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    container_name: frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend
